name: Rust

on: [push]

jobs:
  build_and_test:
    name: Rust Hello World
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - uses: actions-rs/cargo@v1
      - run: cargo build --all --release
